#### Example 01:

In [ ]:
import numpy as np
from IPython.core.completerlib import import_re

list_x=[1,2,3,4] #python list
array = np.array([1, 2, 3, 4, 5, 6]) # single dimensional array
matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]) # nD array

#### Task 01:

**a. What are the results of `print(array[0])`, `print(matrix[1])`, and `matrix[1,2]`?**

**Ans:**
- `print(array[0])`: `1`
- `print(matrix[1])`: `[5, 6, 7, 8]`
- `matrix[1,2]`: `7`

**b. What are the differences between NumPy array and Python list?**

*Hint: write the difference on the basis of the following:*

- **Data type storage**
- **Importing modules**
- **Numerical operations**
- **Memory consumption**
- **Fast and convenient to use**

**Ans:**

1. **Data type storage**
   - NumPy arrays: Store homogeneous data types (all elements same type)
   - Python lists: Can store heterogeneous data types (mixed types allowed)

2. **Importing modules**
   - NumPy arrays: Require `import numpy` to use
   - Python lists: Built-in, no import needed

3. **Numerical operations**
   - NumPy arrays: Support vectorized operations (fast element-wise operations)
   - Python lists: Require loops for element-wise operations

4. **Memory consumption**
   - NumPy arrays: More memory efficient (contiguous memory allocation)
   - Python lists: Less memory efficient (stores pointers to objects)

5. **Fast and convenient to use**
   - NumPy arrays: Optimized for numerical computations (written in C)
   - Python lists: Slower for mathematical operations but more flexible

**c. Using Python function `type()`, find the type of above list/arrays.**

**Ans:**

In [ ]:
import numpy as np
list_x=[1,2,3,4] #python list
array = np.array([1, 2, 3, 4, 5, 6]) # single dimensional array
matrix = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]]) # nD array
print(type(array))
print(type(matrix))

#### Example 02:

In [ ]:
l=[]
for i in range(1,5):
    int_1=int(input("Enter :"))
    l.append(int_1)
print(np.array([l]))

#### Task 02:

**a. Write the result of `print(np.ndim(l))` and `print(np.shape(l))`. What do the functions `ndim()` and `shape()` do?**

**Ans:**

- `print(np.ndim(l))`: `1`
- `print(np.shape(l))`: `(4,)`

**b. Write the result of `np.array([1, 2, 3], ndmin=6)`.**

**Ans:**

- **Result of `np.array([1,2,3], ndmin=6)`:**
```python
[[[[[[1 2 3]]]]]]

#### Example 03:

In [ ]:
arr_zero=np.zeros(4)
arr_zero_2=np.zeros([3,4])
arr_ones=np.ones(3)
arr_em=np.empty(4)
arr_rn=np.arange(4)
arr_dia=np.eye(3)
arr_lin=np.linspace(0,20,num=5)
arr_rand1=np.random.rand(4)
arr_rand2=np.random.rand(2,5)
arr_rand3=np.random.randint(5,20,2)# randint(min, max, number_of_item)

#### Task 03:

**a. Print all the arrays from example 3 and write the functions of each of the NumPy functions.**

**Ans:**

**Functions of each NumPy function:**

1. **`np.zeros(shape)`**
   - Creates an array of the given shape filled with zeros

2. **`np.ones(shape)`**
   - Creates an array of the given shape filled with ones

3. **`np.empty(shape)`**
   - Creates an uninitialized array of the given shape

4. **`np.arange([start, ]stop, [step, ])`**
   - Returns evenly spaced values within an interval

5. **`np.eye(N)`**
   - Creates a 2D identity matrix (ones on diagonal)

6. **`np.linspace(start, stop, num)`**
   - Returns evenly spaced numbers over an interval

7. **`np.random.rand(d0, d1, ..., dn)`**
   - Creates array with random values from [0,1)

8. **`np.random.randint(low, high=None, size=None)`**
   - Returns random integers from low to high

In [ ]:
arr_zero=np.zeros(4)
arr_zero_2=np.zeros([3,4])
arr_ones=np.ones(3)
arr_em=np.empty(4)
arr_rn=np.arange(4)
arr_dia=np.eye(3)
arr_lin=np.linspace(0,20,num=5)
arr_rand1=np.random.rand(4)
arr_rand2=np.random.rand(2,5)
arr_rand3=np.random.randint(5,20,2)# randint(min, max, number_of_item)
print("arr_zero:", arr_zero)
print("arr_zero_2:", arr_zero_2)
print("arr_ones:", arr_ones)
print("arr_em:", arr_em)
print("arr_rn:", arr_rn)
print("arr_dia:", arr_dia)
print("arr_lin:", arr_lin)
print("arr_rand1:", arr_rand1)
print("arr_rand2:", arr_rand2)
print("arr_rand3:", arr_rand3)

**b. Create a 3×4 matrix with all elements equal to zero.**

**Ans:**

In [ ]:
import numpy as np
matrix_zeros = np.zeros((3, 4))
print(matrix_zeros)

#### Example 04:

In [ ]:
#addition and subtraction
arr1 = np.array([[12,34],[44,22]])
arr2 = np.array([[1,34],[0,22]])
arr3 = np.add(arr1,arr2)
arr4 = np.subtract(arr1,arr2)
print(arr3)
print(arr4)

#### Example 05:

In [ ]:
arr1 = np.array([[1,2,3],[2,3,4],[2,3,4]])
arr2 = np.array([[21,4],[2,1],[2,3]])
arr3 = np.dot(arr1, arr2)
arr4 = np.matmul(arr1, arr2)
print(arr3)
print(arr4)
print(np.transpose(arr3))

#### Task 04:

**a. What is the difference between `np.dot()` and `np.matmul()`? What is the result of `np.dot(5, arr1)`?**

**Ans:**

- **`np.dot()`**
  - For 2-D arrays: Performs matrix multiplication
  - For 1-D arrays: Computes the dot product (sum of products)
  - For N-D arrays: Computes sum product over last axis of first array and second-to-last axis of second array

- **`np.matmul()`**
  - For 2-D arrays: Strict matrix multiplication only
  - For N-D arrays: Matrix multiplication along last two axes

- **Result of `np.dot(5, arr1)`:**
  ```python
  [[ 5 10 15]
 [10 15 20]
 [10 15 20]]

**b. What is the result of `np.transpose(arr3)`?**

**Ans:**

- **Result of `np.transpose(arr3)`:**
```python
[[31 56 56]
 [15 23 23]]

**c. How would you scalar multiply the matrix `np.array([[2,3],[4,5]])` by 3?**

**Ans:**

In [ ]:
import numpy as np
matrix = np.array([[2, 3], [4, 5]])
result = matrix * 3
print(result)

#### Example 06:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 5, 20)
y = np.linspace(0, 10, 20)
plt.plot(x, y, 'purple') # line
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Demo graph")
plt.plot(x, y, 'o')
plt.show()

#### Task 05:

**a. Prepare X and Y coordinates values for the function f(x) = 4x^2+2 using NumPy array and plot
the graph using Matplotlib.**

**Ans:**


In [ ]:
import matplotlib.pyplot as plt
x = [1,2,3,4,5]
y = []
for i in x:
    fx = 4 * i ** 2 + 2
    y.append(fx)
plt.plot(x,y)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("f(x) = 4x^2 + 2")
plt.show()

#### Example 07:

**Create two vectors in 2-dimensional (2D) space and plot them using Matplotlib.**

**Solution:** A vector in 2D space can created as a 1D ndarray with two elements as:
```python
V = np.array([1,1])
W = np.array([-2.0,-1])

To plot the above vectors, we will use the quiver() function from the pyplot module of Matplotlib
library. The quiver() function is used to create 2D field or velocity plots and is perfect for our purpose
of vector plotting. Here is an example of plotting the above vectors.



In [ ]:
import numpy as np
import matplotlib.pyplot as plt
""" Problem 2: Create 2-dimensional position vectors and plot them. """
origin = np.array([0,0])
V = np.array([1,1])
W = np.array([-2.0,-1])
fig, ax = plt.subplots()
# Add vectors V and W to the plot
ax.quiver(origin[0], origin[1], V[0], V[1], angles='xy', scale_units='xy', scale=1, color='r')
ax.quiver(origin[0], origin[1], W[0], W[1], angles='xy', scale_units='xy', scale=1, color='b')
ax.text(origin[0]-0.1, origin[1]+0.1, "O")
ax.text(V[0], V[1], "v")
ax.text(W[0]-0.125, W[1]-0.1, "w")
ax.set_xlim([-3, 3])
ax.set_ylim([-3, 3])
ax.set_xlabel('X')
ax.set_ylabel('Y')
plt.grid()
plt.show()

#### Task 06:

**a. Create three vectors in 3D space and plot them using Matplotlib.**

**Ans:**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
U= np.array([1, 0.25 ,0])
V = np.array([0, 1, 0.25])
W = np.array([0.25, 0, 1])
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
plt.plot(U,V,W)
plt.show()

**b. Create two vectors in 2D space, and add them to create a third vector, and plot all three vectors
using Matplotlib.**

**Ans:**

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
U = np.array([-0.5, 0.5])
V = np.array([1,1])
W = U + V # adding two vector
fig = plt.figure()
plt.plot(W)
plt.show()

**c. Write a function to calculate magnitude of a vector. For example, calculate the magnitude of
the vector be U = (1.5, 1.5, 2.0).**

**Ans:**

In [ ]:
import math
U = (1.5, 1.5, 2.0)
mag = 0
for i in U:
    mag += i ** 2
mag = math.sqrt(mag)
print(mag)

**d. Write a function to calculate the direction cosines of the vector. For example, let the vector be
O = (1.5, 1.5, 2.0).**

**Ans**

In [ ]:
import math
O = (1.5, 1.5, 2.0)
mag = 0
for i in U:
    mag += i ** 2
mag = math.sqrt(mag)
for i in U:
    print(i/mag)

**e. Write a function to calculate Scalar (dot) product of two vectors. For example, let the vectors
be a= (1.5, 1.5, 2.0) and b = (−1.5, 0.5, 2.0).**

**Ans:**

In [ ]:
a = (1.5, 1.5, 2.0)
b = (-1.5, 0.5, 2.0)
pro = 0
for i in range(3):
    pro += a[i] * b[i]
print(pro)

**f. Write a function to calculate Vector (cross) product of two vectors. For example, let the vectors
be a = (1.5, 1.5, 2.0) and b= (−1.5, 0.5, 2.0).**

**Ans:**

In [ ]:
import numpy as np
a = (1.5, 1.5, 2.0)
b = (-1.5, 0.5, 2.0)
pro = np.cross(a, b)
print(pro)